[project]
name = "fastapi-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "bcrypt>=5.0.0",
  "betterlogging>=1.0.0",
  "fastapi>=0.141.1",
  "itsdangerous>=2.2.0",
  "pytest>=9.1.1",
  "pytest-asyncio>=1.4.0",
  "pytest-cov>=7.1.0",
  "python-dotenv>=1.2.2",
  "python-multipart>=0.0.32",
  "redis>=8.1.0",
  "tortoise-orm[asyncpg]>=1.1.5",
  "uvicorn>=0.52.0",
  "uvloop>=0.22.1",
]

[tool.tortoise]
tortoise_orm = "app.database.TORTOISE_ORM"

[tool.pytest.ini_options]
asyncio_mode = "auto"
